# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aad5e0b16510baeebebfc684dd7bea57ea19ca28e16758134fb2a02b2ab0275826249de11492cb13712e6a759f65e1329e7fa7d9b915f8d1baf84c55e92fc09b

test:
  secret_key_base: ab810b55d08d37cf88b8de994216ae5a5fcb8c37b45f9b49aaeb1ea9de57198a8411b488c74d49a9fbc258de58b4d6c0ab5171ce51d72480cb678390ce4ded93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
